require: rubocop-rspec

AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - 'spec/fixtures/**/*.rb'
    - 'spec/spec_helper.rb'
  DisplayCopNames: true
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

# That's my style

Layout/LineLength:
  Max: 100
  AllowedPatterns: ['\#.*'] # ignore long comments

Style/AndOr:
  EnforcedStyle: conditionals

Style/FormatString:
  EnforcedStyle: percent

Style/SignalException:
  EnforcedStyle: semantic

Style/BlockDelimiters:
  EnforcedStyle: semantic

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Style/SafeNavigationChainLength:
  Enabled: false

# Auto-correcting is hard job!

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 20

# On it. Honestly
Style/Documentation:
  Enabled: false

# New cops that should always be explicitly turned on or off

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

# Those are meaningless/buggy

Style/CommentAnnotation:
  Enabled: false
