---
# For all TheSchemaIs cops the settings are the same.
# But note that Rubocop's behavior is slightly weird with --show-cops (it will not show that
# cop has those three setting)
TheSchemaIs:
  Schema: db/schema.rb
  BaseClass: ['ActiveRecord::Base', 'ApplicationRecord']
  TablePrefix: ''
  RemoveDefinitions: []

TheSchemaIs/Presence:
   Description: "Check presence of the_schema_is statement in ActiveRecord models"
   Enabled: true

TheSchemaIs/WrongTableName:
   Description: "Check table name define by the_schema_is statement against one in schema.rb"
   Enabled: true

TheSchemaIs/MissingColumn:
  Description: "Check columns missing in the_schema_is definition (but present in schema.rb)"
  Enabled: true

TheSchemaIs/UnknownColumn:
  Description: "Check unknown column in the_schema_is definition (not defined in schema.rb)"
  Enabled: true

TheSchemaIs/WrongColumnDefinition:
  Description: "Check column definition in the_schema_is statement against schema.rb"
  Enabled: true
