inherit_from: ../.rubocop.yml

Style/BlockDelimiters:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
